package cn.wangziwei.mybatis.pojo;

import java.util.Date;

public class LogEmp {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.id
     *
     * @mbggenerated Sun Dec 25 00:21:20 CST 2022
     */
    private Long id;

    @Override
    public String toString() {
        return "LogEmp{" +
                "id=" + id +
                ", oppeoplename='" + oppeoplename + '\'' +
                ", logtime=" + logtime +
                ", logtypeenum='" + logtypeenum + '\'' +
                ", value='" + value + '\'' +
                ", keyid='" + keyid + '\'' +
                '}';
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.opPeopleName
     *
     * @mbggenerated Sun Dec 25 00:21:20 CST 2022
     */
    private String oppeoplename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.logTime
     *
     * @mbggenerated Sun Dec 25 00:21:20 CST 2022
     */
    private Date logtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.logTypeEnum
     *
     * @mbggenerated Sun Dec 25 00:21:20 CST 2022
     */
    private String logtypeenum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.value
     *
     * @mbggenerated Sun Dec 25 00:21:20 CST 2022
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.keyId
     *
     * @mbggenerated Sun Dec 25 00:21:20 CST 2022
     */
    private String keyid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.id
     *
     * @return the value of log.id
     *
     * @mbggenerated Sun Dec 25 00:21:20 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.id
     *
     * @param id the value for log.id
     *
     * @mbggenerated Sun Dec 25 00:21:20 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.opPeopleName
     *
     * @return the value of log.opPeopleName
     *
     * @mbggenerated Sun Dec 25 00:21:20 CST 2022
     */
    public String getOppeoplename() {
        return oppeoplename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.opPeopleName
     *
     * @param oppeoplename the value for log.opPeopleName
     *
     * @mbggenerated Sun Dec 25 00:21:20 CST 2022
     */
    public void setOppeoplename(String oppeoplename) {
        this.oppeoplename = oppeoplename == null ? null : oppeoplename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.logTime
     *
     * @return the value of log.logTime
     *
     * @mbggenerated Sun Dec 25 00:21:20 CST 2022
     */
    public Date getLogtime() {
        return logtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.logTime
     *
     * @param logtime the value for log.logTime
     *
     * @mbggenerated Sun Dec 25 00:21:20 CST 2022
     */
    public void setLogtime(Date logtime) {
        this.logtime = logtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.logTypeEnum
     *
     * @return the value of log.logTypeEnum
     *
     * @mbggenerated Sun Dec 25 00:21:20 CST 2022
     */
    public String getLogtypeenum() {
        return logtypeenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.logTypeEnum
     *
     * @param logtypeenum the value for log.logTypeEnum
     *
     * @mbggenerated Sun Dec 25 00:21:20 CST 2022
     */
    public void setLogtypeenum(String logtypeenum) {
        this.logtypeenum = logtypeenum == null ? null : logtypeenum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.value
     *
     * @return the value of log.value
     *
     * @mbggenerated Sun Dec 25 00:21:20 CST 2022
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.value
     *
     * @param value the value for log.value
     *
     * @mbggenerated Sun Dec 25 00:21:20 CST 2022
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.keyId
     *
     * @return the value of log.keyId
     *
     * @mbggenerated Sun Dec 25 00:21:20 CST 2022
     */
    public String getKeyid() {
        return keyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.keyId
     *
     * @param keyid the value for log.keyId
     *
     * @mbggenerated Sun Dec 25 00:21:20 CST 2022
     */
    public void setKeyid(String keyid) {
        this.keyid = keyid == null ? null : keyid.trim();
    }
}