package cn.wangziwei.mybatis.pojo;

import java.util.Date;

public class LogOpEmp {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_op.id
     *
     * @mbggenerated Sun Dec 25 00:21:20 CST 2022
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_op.opPeopleName
     *
     * @mbggenerated Sun Dec 25 00:21:20 CST 2022
     */
    private String oppeoplename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_op.logTime
     *
     * @mbggenerated Sun Dec 25 00:21:20 CST 2022
     */
    private Date logtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_op.logTypeEnum
     *
     * @mbggenerated Sun Dec 25 00:21:20 CST 2022
     */
    private String logtypeenum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_op.value
     *
     * @mbggenerated Sun Dec 25 00:21:20 CST 2022
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_op.itemkey
     *
     * @mbggenerated Sun Dec 25 00:21:20 CST 2022
     */
    private String itemkey;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_op.id
     *
     * @return the value of log_op.id
     *
     * @mbggenerated Sun Dec 25 00:21:20 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_op.id
     *
     * @param id the value for log_op.id
     *
     * @mbggenerated Sun Dec 25 00:21:20 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_op.opPeopleName
     *
     * @return the value of log_op.opPeopleName
     *
     * @mbggenerated Sun Dec 25 00:21:20 CST 2022
     */
    public String getOppeoplename() {
        return oppeoplename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_op.opPeopleName
     *
     * @param oppeoplename the value for log_op.opPeopleName
     *
     * @mbggenerated Sun Dec 25 00:21:20 CST 2022
     */
    public void setOppeoplename(String oppeoplename) {
        this.oppeoplename = oppeoplename == null ? null : oppeoplename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_op.logTime
     *
     * @return the value of log_op.logTime
     *
     * @mbggenerated Sun Dec 25 00:21:20 CST 2022
     */
    public Date getLogtime() {
        return logtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_op.logTime
     *
     * @param logtime the value for log_op.logTime
     *
     * @mbggenerated Sun Dec 25 00:21:20 CST 2022
     */
    public void setLogtime(Date logtime) {
        this.logtime = logtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_op.logTypeEnum
     *
     * @return the value of log_op.logTypeEnum
     *
     * @mbggenerated Sun Dec 25 00:21:20 CST 2022
     */
    public String getLogtypeenum() {
        return logtypeenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_op.logTypeEnum
     *
     * @param logtypeenum the value for log_op.logTypeEnum
     *
     * @mbggenerated Sun Dec 25 00:21:20 CST 2022
     */
    public void setLogtypeenum(String logtypeenum) {
        this.logtypeenum = logtypeenum == null ? null : logtypeenum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_op.value
     *
     * @return the value of log_op.value
     *
     * @mbggenerated Sun Dec 25 00:21:20 CST 2022
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_op.value
     *
     * @param value the value for log_op.value
     *
     * @mbggenerated Sun Dec 25 00:21:20 CST 2022
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_op.itemkey
     *
     * @return the value of log_op.itemkey
     *
     * @mbggenerated Sun Dec 25 00:21:20 CST 2022
     */
    public String getItemkey() {
        return itemkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_op.itemkey
     *
     * @param itemkey the value for log_op.itemkey
     *
     * @mbggenerated Sun Dec 25 00:21:20 CST 2022
     */
    public void setItemkey(String itemkey) {
        this.itemkey = itemkey == null ? null : itemkey.trim();
    }
}