spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/people
    username: root
    password: root
mybatis:
  config-location: classpath:mybatis-config.xml