package cn.wangziwei.mybatis.mapper;

import cn.wangziwei.mybatis.pojo.LogEmp;
import cn.wangziwei.mybatis.pojo.LogEmpExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface LogEmpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbggenerated Sun Dec 25 00:21:20 CST 2022
     */
    int countByExample(LogEmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbggenerated Sun Dec 25 00:21:20 CST 2022
     */
    int deleteByExample(LogEmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbggenerated Sun Dec 25 00:21:20 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbggenerated Sun Dec 25 00:21:20 CST 2022
     */
    int insert(LogEmp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbggenerated Sun Dec 25 00:21:20 CST 2022
     */
    int insertSelective(LogEmp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbggenerated Sun Dec 25 00:21:20 CST 2022
     */
    List<LogEmp> selectByExample(LogEmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbggenerated Sun Dec 25 00:21:20 CST 2022
     */
    LogEmp selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbggenerated Sun Dec 25 00:21:20 CST 2022
     */
    int updateByExampleSelective(@Param("record") LogEmp record, @Param("example") LogEmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbggenerated Sun Dec 25 00:21:20 CST 2022
     */
    int updateByExample(@Param("record") LogEmp record, @Param("example") LogEmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbggenerated Sun Dec 25 00:21:20 CST 2022
     */
    int updateByPrimaryKeySelective(LogEmp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbggenerated Sun Dec 25 00:21:20 CST 2022
     */
    int updateByPrimaryKey(LogEmp record);
}