package cn.wangziwei.mybatis.mapper;

import cn.wangziwei.mybatis.pojo.LogOpEmp;

import java.util.List;

import cn.wangziwei.mybatis.pojo.LogOpEmpExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface LogOpEmpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_op
     *
     * @mbggenerated Sun Dec 25 00:21:20 CST 2022
     */
    int countByExample(LogOpEmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_op
     *
     * @mbggenerated Sun Dec 25 00:21:20 CST 2022
     */
    int deleteByExample(LogOpEmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_op
     *
     * @mbggenerated Sun Dec 25 00:21:20 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_op
     *
     * @mbggenerated Sun Dec 25 00:21:20 CST 2022
     */
    int insert(LogOpEmp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_op
     *
     * @mbggenerated Sun Dec 25 00:21:20 CST 2022
     */
    int insertSelective(LogOpEmp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_op
     *
     * @mbggenerated Sun Dec 25 00:21:20 CST 2022
     */
    List<LogOpEmp> selectByExample(LogOpEmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_op
     *
     * @mbggenerated Sun Dec 25 00:21:20 CST 2022
     */
    LogOpEmp selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_op
     *
     * @mbggenerated Sun Dec 25 00:21:20 CST 2022
     */
    int updateByExampleSelective(@Param("record") LogOpEmp record, @Param("example") LogOpEmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_op
     *
     * @mbggenerated Sun Dec 25 00:21:20 CST 2022
     */
    int updateByExample(@Param("record") LogOpEmp record, @Param("example") LogOpEmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_op
     *
     * @mbggenerated Sun Dec 25 00:21:20 CST 2022
     */
    int updateByPrimaryKeySelective(LogOpEmp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_op
     *
     * @mbggenerated Sun Dec 25 00:21:20 CST 2022
     */
    int updateByPrimaryKey(LogOpEmp record);
}