package cn.wangziwei.mybatis.mapper;

import cn.wangziwei.mybatis.pojo.PeopleEmp;
import cn.wangziwei.mybatis.pojo.PeopleEmpExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PeopleEmpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table people
     *
     * @mbggenerated Sun Dec 25 01:24:20 CST 2022
     */
    int countByExample(PeopleEmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table people
     *
     * @mbggenerated Sun Dec 25 01:24:20 CST 2022
     */
    int deleteByExample(PeopleEmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table people
     *
     * @mbggenerated Sun Dec 25 01:24:20 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table people
     *
     * @mbggenerated Sun Dec 25 01:24:20 CST 2022
     */
    int insert(PeopleEmp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table people
     *
     * @mbggenerated Sun Dec 25 01:24:20 CST 2022
     */
    int insertSelective(PeopleEmp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table people
     *
     * @mbggenerated Sun Dec 25 01:24:20 CST 2022
     */
    List<PeopleEmp> selectByExample(PeopleEmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table people
     *
     * @mbggenerated Sun Dec 25 01:24:20 CST 2022
     */
    PeopleEmp selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table people
     *
     * @mbggenerated Sun Dec 25 01:24:20 CST 2022
     */
    int updateByExampleSelective(@Param("record") PeopleEmp record, @Param("example") PeopleEmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table people
     *
     * @mbggenerated Sun Dec 25 01:24:20 CST 2022
     */
    int updateByExample(@Param("record") PeopleEmp record, @Param("example") PeopleEmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table people
     *
     * @mbggenerated Sun Dec 25 01:24:20 CST 2022
     */
    int updateByPrimaryKeySelective(PeopleEmp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table people
     *
     * @mbggenerated Sun Dec 25 01:24:20 CST 2022
     */
    int updateByPrimaryKey(PeopleEmp record);
}